### ISSUE TITLE
Exclusions fail for locally abstract types

### ISSUE THREAD

**Issue by simonjbeaumont** [rleonid/bisect_ppx#15]
When using locally abstract types, the exclusions do not work. I have created a branch of this repo and added a (failing) testcase here:

https://github.com/rleonid/bisect_ppx/compare/rleonid:master...simonjbeaumont:locally-abstract-types

The preprocessor should not add instrumentation to this function since it matches the regexp in the `exclusions` file. However it does:

```
$ make -C tests one NAME=ppx-exclude-file
make: Entering directory `/local/work/code/bisect_ppx/tests'
Running tests for 'ppx-exclude-file'...
make[1]: Entering directory `/local/work/code/bisect_ppx/tests/ppx-exclude-file'
     testing 'source.ml' ...
Files source.ml.reference and source.ml.result differ
make[1]: *** [default] Error 1
make[1]: Leaving directory `/local/work/code/bisect_ppx/tests/ppx-exclude-file'
make: Leaving directory `/local/work/code/bisect_ppx/tests'
```

```diff
$ (cd tests/ppx-exclude-file; diff -u source.ml.reference source.ml.result)
--- source.ml.reference 2015-06-08 15:22:37.932377656 +0100
+++ source.ml.result    2015-06-08 15:27:43.124377656 +0100
@@ -4,4 +4,10 @@
   Bisect.Runtime.mark "source.ml" 1;
   for i = 1 to 5 do (Bisect.Runtime.mark "source.ml" 0; print_endline s) done
 let f2 b x = if b then x * x else x
-let f3 : 'a . 'a -> string= fun (type a) -> (fun _  -> "Hello" : a -> string)
+let f3 : 'a . 'a -> string=
+  Bisect.Runtime.mark "source.ml" 2;
+  fun
+  (type
+  a)
+  ->
+  ((fun _  -> "Hello") : a -> string)
```

I generated the additional code in the `.reference` file using the `(*BISECT-IGNORE-BEGIN/END*)` bracketing.

My motivation for this is my use of this extension with https://github.com/simonjbeaumont/ocaml-pci which uses ctypes to generate bindings and ctypes uses code of the above form. I want to exclude the generated code from my results.

I might take a look around the code when I get a change see if I can come up with a pull request but any pointers would be appreciated.

Thanks in advance!

**Comment by rleonid** [comment]
I'll take a look today.

**Comment by rleonid** [comment]
@simonjbeaumont thanks for the bug report and the useful test case. Please see PR #19 and let me know if it fixes other use cases that you might have. I did not do a full examination of the possible places in the `OCaml` AST where this could apply, just narrowed down your use case.

**Comment by simonjbeaumont** [comment]
Cool! I'll take a look this afternoon

**Comment by simonjbeaumont** [comment]
Looks like it did the trick for me!
Before:
![2015-06-12-161032_743x594_scrot](https://cloud.githubusercontent.com/assets/1125539/8133048/9fab78e0-111d-11e5-94a4-39b849a9d75a.png)

After:
![new](https://cloud.githubusercontent.com/assets/1125539/8133107/08c938e4-111e-11e5-88e9-9b84e4b708c3.png)

This is excluding like this:
```file "lib/ffi_generated_types.ml" [ regexp ".*" ];```


I'm excluding this with an exclude file like this:

**Comment by simonjbeaumont** [comment]
I'll keep an eye out for a new OPAM release! Thanks @rleonid!

**Comment by rleonid** [comment]
Awesome. Do you have any comments or concerns about this PR #18 ? I wouldn't want this to break any of your stuff either, but it might require changing some shell scripting logic if you rely on incrementally numbered reports. I remember you were using `OUnit` in another issue?

**Comment by simonjbeaumont** [comment]
I'm not relying on specifics rather I delete all the bisect files using `find` and then run my test and gather the output using a glob.
