### ISSUE TITLE
Change the testing infrastructure

### ISSUE THREAD

**Issue by rleonid** [rleonid/bisect_ppx#2]
Currently it's a file comparison against a reference. This needs to be less brittle and, for example, ignore space issues.

**Comment by aantron** [comment]
Any objections to me taking this on and trying to convert most of the tests to, for example, oUnit? If properly written, that should make it easier to edit the code to uniformly take care of space issues or other concerns. I am not sure how practical that is, but oUnit does have [`assert_command`](http://ounit.forge.ocamlcore.org/api-ounit/OUnit2.html#VALassert_command), so it should be relatively easy to start builds with the extension from inside a test suite.

**Comment by rleonid** [comment]
No objective at all, I would very much appreciate the help!

In general, I would prefer a property test driven approach, which, as far as I understand `OUnit` does not support. But I think that kind of test suite might be harder (and take longer) to write, and since I haven't yet used `OUnit` it would be a great opportunity for me to learn. So, yea, 2 thumbs up :+1: :+1: !

**Comment by aantron** [comment]
I'll use OUnit. As I understand it, it should be possible to write our own little property-driven tester on top of OUnit, but I am not going to do that right now.

**Comment by dsheets** [comment]
Another option is [alcotest](https://github.com/mirage/alcotest) which has some nice UI and logging features (color output, nice command line flag support, easy test selection, output recording) compared to OUnit. OUnit 2 in particular is rather clunky compared to OUnit 1 and a lot of projects end up using the OUnit 1 legacy interface of the OUnit 2 package.

Just a suggestion to look at. OUnit and alcotest aren't so different at their hearts.

**Comment by aantron** [comment]
Thanks, it looks interesting.

**Comment by rleonid** [comment]
By-the-way, extra bonus points, if there is a coverage report (using `bisect_ppx`, of course) for this test suite!

**Comment by aantron** [comment]
Exactly what I was thinking :) I was going to also suggest posting it as part of GH pages for bisect_ppx, as well as one or two rounds of HTML cleanup (readability, then aesthetics).

**Comment by rleonid** [comment]
That would be awesome.

**Comment by simonjbeaumont** [comment]
You could push to coveralls as well using this (which builds on bisect_ppx): https://github.com/simonjbeaumont/ocaml-travis-coveralls

**Comment by aantron** [comment]
Yes :) Part of the plan, but I wanted to discuss alternatives to coveralls first. I don't have a particular reason, just not sure if there are any good ones...

I also want to update and/or rewrite the manual and update the README.

On the technical side, I'm considering adding points to or-patterns:

```ocaml
match blah with
| (* here *) A | (* here *) B -> ...
```

though this would be a non-trivial translation.

**Comment by simonjbeaumont** [comment]
The big downside to coveralls for storing bisect data is that it's sensitive to coding style. That is because bisect uses points of which there can be many points on a line and the percentage coverage is given as a percentage of points covered. However, coveralls' API works only with lines. What ocveralls does is say that all points on a line should be covered for the coveralls line to be marked as covered. This is the safest and conservative approach however it leads to a mismatch in the numbers for most codebases.

**Comment by aantron** [comment]
That is true, but I think we will put up both a bisect_ppx HTML report on GitHub pages and also link to coveralls. I was wondering if you could recommend any other "popular" service that allows browsing coverage reports, especially if it deals with points and not lines.

Maybe we should add an output mode to bisect_ppx that converts the coverage total into a link to a shields.io badge :) Of course, this could also be a simple script instead...
