### ISSUE TITLE
Test rewriters in both order.

### ISSUE THREAD

**Issue by rleonid** [rleonid/bisect_ppx#35]
Bisect_ppx needs to work well with other ppx rewriters in any order:
`ppx_deriving` -> `bisect_ppx`  and `bisect_ppx` -> `ppx_deriving`

**Comment by aantron** [comment]
Do you recall what the difficulties were with this? I saw in the old tests that `ppx_deriving` was only tested one way, and there were also unused files for `ppx_getenv` (IIRC).

**Comment by rleonid** [comment]
I don't immediately remember the difference, I just would make sure that there is a test that allows one to write the rewriters in any order. I'm not certain if the output should be the same.
