### ISSUE TITLE
Fix OS X tests in Travis

### ISSUE THREAD

**Issue by aantron** [rleonid/bisect_ppx#37]
The tests don't account for context information inserted by the compiler since 4.02.3. Should take care of this problem before merging #34. Not exactly sure why this is a problem only in that build only in Travis, but will look into it.

Original compiler feature request: http://caml.inria.fr/mantis/view.php?id=6497

**Comment by aantron** [comment]
@rleonid this is now fixed by the latest commit. See the commit message for a full description. If you are okay with this, fast-forward `master` over it (or I can do it). I didn't feel this is worth a full PR (let me know if you think otherwise). I will then rebase the OUnit PR over `master` and squash it to two commits. It should then be ready for merging as well.

**Comment by rleonid** [comment]
Go for it! I've added you as a collaborator on the project. You're making some good choices, digging into the details and solving problems, thank you!

**Comment by aantron** [comment]
Ok, thank you :)
