### ISSUE TITLE
Eliminate ./configure script and unnecessary files

### ISSUE THREAD

**Issue by aantron** [rleonid/bisect_ppx#40]
The `./configure` script doesn't provide very much. All the variables are either trivial or unused, except for the paths, which interfere with OPAM in the following way: if you run `opam switch`, you then need to rerun `./configure` again for the build system to pick up the change. I say we should just use `ocamlc` and `ocamlfind` directly, and get rid of `./configure`.

Also, there are a lot of redundant files in the root directory: `FEATURE` and `README` (not `.md`), `INSTALL`, and `VERSION`, that are there for an old source distribution convention, which doesn't matter when installing from OPAM, or just dealing with modern software in general. We should delete them. This will also make it easier to reach `README.md` on the GitHub page, a small but nice benefit, especially when we update the README :)

**Comment by rleonid** [comment]
Agree 100%

**Comment by rleonid** [comment]
Taken care of by #39
