### ISSUE TITLE
Improve legibility of HTML output

### ISSUE THREAD

**Issue by aantron** [rleonid/bisect_ppx#42]
Apart from aesthetics, there are two main issues with the HTML output:

- At least on my system, `~` and `-` are nearly indistinguishable in Courier New when it is late and my eyes are tired. We should prepend some more modern monospace fonts before Courier New in the stylesheet to deal with this. If the fonts are not available, Courier New or whatever system monospace font will still be a fallback.
- The red background color is too dark and does not contrast enough with the black text.

**Comment by rleonid** [comment]
Sounds good.
