### ISSUE TITLE
Add points to each clause of or-patterns

### ISSUE THREAD

**Issue by aantron** [rleonid/bisect_ppx#43]
Not yet sure if this is reasonable, but I want to look into adding this translation:

```ocaml
match foo with
| `P1 -> e1
| _, (`P2 | `P3 as x) as y -> e2
```

to

```ocaml
let e2' x y = e2 in
match foo with
| `P1 -> point 1; e1
| _, (`P2 as x) as y -> point 2; e2' x y
| _, (`P3 as x) as y -> point 3; e2' x y
```

and reporting as

```ocaml
match foo with
| (* point 1 *) `P1 -> e1
| _, ((* point 2 *) `P2 | (* point 3 *) `P3 as x) as y -> e2
```

In case of nested or-patterns, the point would be on the deepest clauses. In case of a product of or-patterns, I am not sure what to do. There is both a combinatorial blow-up and no good place to put a point. Since Bisect_ppx explicitly doesn't try to understand execution paths, just whether execution passes by a point, this whole thing might be against the spirit of the tool anyway and a bad idea. In that case, I we should briefly mention why we don't do this in some new documentation we may write later.

@rleonid thoughts?

**Comment by aantron** [comment]
I suppose we could translate

```ocaml
| (`P1 | `P2), (`P3 | `P4) -> e
```

to

```ocaml
match foo with
| `P1, `P3 -> point 1; point 3; e' ()
| `P1, `P4 -> point 1; point 4; e' ()
| `P2, `P3 -> point 2; point 3; e' ()
| `P2, `P4 -> point 2; point 4; e' ()
```

i.e. count visits to the clauses independently instead of trying to count visits to elements of the cross product.

In any case, this kind of translation would help me to test automata in Markup.ml much more thoroughly.

**Comment by rleonid** [comment]
I'm a bit confused, your original example doesn't compile; the first branch is a variant and the second a tuple. Did you mean:
```Ocaml
match foo with
| `P1 -> e1
| (`P2 | `P3 as x) as y -> e2
```

**Comment by aantron** [comment]
Yes :) I changed the patterns from `p1` to `` `P1`` at the last moment and wasn't careful updating it.

**Comment by rleonid** [comment]
I think a simpler way of rewriting the original example would be:
```OCaml
match foo with
| `P1 -> Bisect.mark 0; e1
| (`P2 | `P3 as x) -> (match x with `P2 -> Bisect.mark 1 | `P3 -> Bisect.mark 2); e2
```
This has the advantage of being a simpler recursive map of the [`Ppat_or`](https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli#L203) pattern

**Comment by aantron** [comment]
I think the recursive map is ultimately the same, just the interpretation (what is being constructed as a result of it) is different, but this is a good idea. It doesn't change the "real" case list entered by the user, which keeps instrumented code resistant to bugs in Bisect_ppx, among other things. Thanks.
