### ISSUE TITLE
Fix packaging

### ISSUE THREAD

**Issue by aantron** [rleonid/bisect_ppx#54]
I'm noting this for later, because it's probably best done after the "big" changes are in, but:

- Using `git describe` to generate `version.ml` probably means that our code can't be built without a git repo, e.g. if downloaded by OPAM from the GH releases link. We need another way of generating this file, but I would also suggest just hardcoding it (it's no worse than having `VERSION` like before), and adopting a habit of doing a `grep` for the old version number when bumping versions.
- Need to edit the tests section in `opam` to do `make dev` before `make tests`.
- I don't think the `str` dependency in `META` is necessary, since `str` gets linked into the binaries but is not needed for the runtime. Haven't tested.

**Comment by rleonid** [comment]
- Update the `CHANGES` 
- I also started keeping a "caveats" section at the end of the README.

**Comment by aantron** [comment]
- Add a release checklist to the docs :)

**Comment by aantron** [comment]
https://github.com/rleonid/bisect_ppx/blob/master/opam/files/bisect_ppx.install#L3

Are there platforms, configurations, or switches for which the native version won't be installed?
