### ISSUE TITLE
Support bytecode architectures

### ISSUE THREAD

**Issue by aantron** [rleonid/bisect_ppx#63]
Our `.itarget` file causes us to build the native reporter unconditionally. We may want to relax that in light of this thread https://sympa.inria.fr/sympa/arc/caml-list/2016-01/msg00038.html

**Comment by rleonid** [comment]
Agreed, that was most likely one of the good reasons for the complicated build system that I threw out :smile:

**Comment by aantron** [comment]
Well, that, and that it didn't assume `ocamlfind` :) I think now we can just add a check `which ocamlopt` and generate/update the `.itarget` files based on it... or just list the targets in the `Makefile`.

While we're at it, we should check if the performance difference between the native instrumenter and the bytecode instrumenter is significant, and install the native one if it is faster (if also supported).

**Comment by aantron** [comment]
Regarding the performance difference, I ran tests with command lines

```sh
time ocamlfind (c|opt) (-package bisect_ppx)? -c expr_match.ml
```

where the rewriter was either bytecode or native code. Here are the averaged results I got on my system:

```
ocamlc                          28ms
ocamlc + bisect_ppx.byte        57ms
ocamlc + bisect_ppx.native      45ms

ocamlopt                        62ms
ocamlopt + bisect_ppx.byte     106ms
ocamlopt + bisect_ppx.native    95ms
```

This suggests that, at least for relatively small source files, when there aren't many other packages (and probably, especially, other ppx rewriters), the bytecode rewriter takes about as long as the rest of `ocamlc` (29ms), and about 2/3 as long as `ocamlopt` (44ms). So, it may be worth optimizing.

Using the native rewriter reduces this to 17ms and 33ms, respectively, improvements of 41% and 25%, respectively. I think we should install the native version whenever possible, so I'll start working on a PR.

This doesn't test the relative importance of rewriter start-up time compared to processing time on a large AST. I also don't know why the same rewriter seems to take a different amount of time depending on whether `ocamlopt` or `ocamlc` is driving it.

**Comment by rleonid** [comment]
This is a good start and probably having the native version around will be useful. I only have 2 comments that might be useful.

1. bisect_ppx is just symbol manipulation; my understanding is that moving around pointers should have similar performance between the two.
2. To get more robust measurements I would just create a profiled version of `bisect_ppx.ml`, that spits out the time used in the 'main' function. This requires more work, and isn't 100% accurate since it doesn't take into account start-up time. But it should remove the bias of the `ocaml(c|opt)`,

**Comment by aantron** [comment]
Perhaps we should open an issue for doing the measurement the proper way. As you say, it would take some work, and I don't think it's a very high priority. For now, I propose installing native binaries as a side effect of fixing this issue.

**Comment by rleonid** [comment]
Agreed.
