### ISSUE TITLE
Release including performance improvements?

### ISSUE THREAD

**Issue by yallop** [rleonid/bisect_ppx#79]
The current release of bisect_ppx sometimes leads to timed-out Travis tests, perhaps due to some kind of deadlock in the instrumented code.  The problem disappears after #50 is merged.  Could you please release a version of bisect_ppx that includes those changes?

**Comment by aantron** [comment]
Absolutely. We are finishing up the last bits before release. It should be possible to do it today.

**Comment by yallop** [comment]
Thanks!
