### ISSUE TITLE
Support regex in filename exclusions

### ISSUE THREAD

**Issue by solongordon** [rleonid/bisect_ppx#89]
Currently it looks like although top-level values can be excluded by regex, excluded filenames must be specified exactly in the exclusion file. It would be great to support regex for filenames as well, for example to allow excluding unit tests themselves from coverage via `^test_.*`.

**Comment by aantron** [comment]
@solongordon If you are using Ocamlbuild and the plugin, you should be able to achieve this effect with a line like

```
<**/test_*>: -coverage
```

Let us know if that doesn't help.

**Comment by aantron** [comment]
(Note) without the plugin, you should be able to do `-package(bisect_ppx)` instead.

**Comment by solongordon** [comment]
Thanks for the suggestion. We're using OMake so unfortunately we can't use the _tags approach.

We can certainly get by with the currently exclusion file format, and/or by only building some files with bisect_ppx enabled, but it would be more convenient to exclude via glob or regex.

**Comment by rgrinberg** [comment]
Just a heads up, excluding all the test files using ppx_bisect in omake was easy enough but we found skipping out on some other generated files to be easier done with ppx_bisect's config file.

We thought it would just be better if all of those settings lived in 1 place.

PS: I work with @solongordon

**Comment by aantron** [comment]
Just to be clear: by config file you mean the exclusion file (for option `-exclude_file`)?

**Comment by solongordon** [comment]
Yup, exactly.

**Comment by aantron** [comment]
Are you okay with using the dev version of Bisect_ppx for now? The release to OPAM is blocked on some 4.03-related questions for a bit. If you would prefer the updated Bisect_ppx be available in OPAM rather than using a dev version, I can make a release including this change but without 4.03 compatibility.

**Comment by solongordon** [comment]
Yes, no rush on the OPAM release. Thanks again.
