### ISSUE TITLE
Compilation failure if a string contains 2 backslashes at the end

### ISSUE THREAD

**Issue by Khady** [rleonid/bisect_ppx#9]
Hello,

I'm not able to compile a file which contains strings with backslashes.
I'm using the 0.2 release from opam.

Here is an example:

```
$ ls                                                                             
actors.ml  test.ml
$ cat actors.ml 
type t =
  | Anthony
  | Caesar
  | Cleopatra

let message = function
  | Anthony     -> "foo\\"
  | Caesar      -> "\\bar"
  | Cleopatra   -> "Fool! Don't you see now that I could have poisoned you\
                    a hundred times had I been able to live without you."
$ cat test.ml
open Actors

let () =
  print_endline (message Cleopatra);
  print_endline (message Anthony);
$ ocamlfind ocamlc -package bisect_ppx -linkpkg actors.ml test.ml -o test.covered
lexing error at line 11: unexpected end of file
File "actors.ml", line 1:
Error: Error while running external preprocessor
Command line: /home/louis/.opam/4.02.1+PIC/lib/bisect_ppx/./bisect_ppx.byte '/tmp/camlppx5982c4' '/tmp/camlppxdb6336'
```

**Comment by rleonid** [comment]
Thanks for submitting. I think the issue is with the original `Bisect` specific comment parsing. I'll take a look as soon as I can.

**Comment by Khady** [comment]
Actually it fails without the comments. I removed them.

I am able to compile the file with the camlp4 version of bisect.

**Comment by rleonid** [comment]
Sorry, I meant the special `Bisect` comments: `(*BISECT-MARK*)` and company. I'll admit that I haven't fully grokked how that code works, and there are probably other bugs related to it.

I think I fixed this obvious case in https://github.com/rleonid/bisect_ppx/pull/11. Could you please confirm.

**Comment by Khady** [comment]
Indead it works. Thanks for the quick fix!
